name: automerge

on:
  pull_request:
    types: [labeled, opened, reopened, ready_for_review, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    name: merge when green
    if: (contains(github.event.pull_request.labels.*.name, 'automerge') || github.event.pull_request.head.ref == 'chore/ruff-and-ci-cleanup') && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge (squash) with gh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR=${{ github.event.pull_request.number }}
          TITLE="auto-merge: ${{ github.event.pull_request.title }} (#${{ github.event.pull_request.number }})"
          BODY="${{ github.event.pull_request.body }}"
          gh pr merge "$PR" --squash --auto --delete-branch --subject "$TITLE" --body "$BODY"