name: CI

on:
  # Run tests on PRs to main before merge, and on pushes to any branch
  pull_request:
    branches: [ main ]
  push:
    branches: [ "**" ]

jobs:
  tests-lint-type:
    name: Tests, Lint, Typecheck (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.11' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest ruff mypy
      - name: Run tests
        run: pytest -q
      - name: Lint (ruff)
        run: ruff check .
      - name: Type check (mypy)
        run: mypy .
